/* ══════════════════════════════════════════════════════════════════
   LOGO → INLINE SVG MODULE

       node scripts/build-logo.mjs

   Turns src/assets/brand/logo-full.svg into a TypeScript constant the
   voucher can embed directly.

   ⚠️ Why generate rather than hand-copy. The voucher must be a single
   self-contained file — it is printed, downloaded and opened offline
   at front desks — so the logo has to live inside the markup. Pasting
   5KB of path data into a .ts file by hand is how a logo silently
   drifts from the brand asset. Re-run this instead.
   ══════════════════════════════════════════════════════════════════ */

import { readFileSync, writeFileSync } from "node:fs";

const SOURCE = "src/assets/brand/logo-full.svg";
const TARGET = "src/assets/brand/logoMarkup.ts";

let svg = readFileSync(SOURCE, "utf8");

svg = svg
  .replace(/<\?xml[^>]*\?>/g, "")
  .replace(/<!DOCTYPE[^>]*>/gi, "")
  .replace(/<!--[\s\S]*?-->/g, "")
  .replace(/>\s+</g, "><")
  .trim();

/* The asset carries width/height in user units, which would pin the
   lockup at 3825px wide. Dropping them leaves the viewBox to scale it. */
svg = svg.replace(/\s(width|height)="[^"]*"/g, "");

// Escape for embedding in a TS template literal.
const escaped = svg
  .replace(/\\/g, "\\\\")
  .replace(/`/g, "\\`")
  .replace(/\$\{/g, "\\${");

const out = `/* ══════════════════════════════════════════════════════════════════
   THE FIDATO WORDMARK, AS INLINE SVG

   ⚠️ GENERATED by scripts/build-logo.mjs from ${SOURCE}.
   Do not hand-edit — re-run the script if the brand asset changes.

   ⚠️ Inline, not an <img>. The voucher is printed, downloaded and
   opened offline at front desks with no network. A linked image would
   render as a broken box in exactly the situation the document exists
   for.

   ⚠️ THE EMAIL CANNOT USE THIS. Gmail strips <svg> outright and blocks
   data: URIs inside <img>, so the covering email points at a hosted
   PNG instead. Two carriers for one logo is what email clients cost,
   not an oversight — see LOGO_PNG_URL in features/reservations/voucher.
   ══════════════════════════════════════════════════════════════════ */

/** Full lockup: mark + FIDATO + HOTELS. Aspect ratio 3825.24 x 1082.04. */
export const FIDATO_LOGO_SVG = \`${escaped}\`;

const ASPECT = 1082.04 / 3825.24;

/**
 * The lockup at a given pixel width, height derived from the real
 * aspect ratio rather than guessed.
 */
export function fidatoLogo(widthPx: number): string {
  const height = Math.round(widthPx * ASPECT);
  return FIDATO_LOGO_SVG.replace(
    "<svg ",
    \`<svg width="\${widthPx}" height="\${height}" \`,
  );
}

/* Brand colours read off the logo itself, so the document and the mark
   can never disagree about what Fidato orange is. */
export const BRAND_INK = "#142B3A";
export const BRAND_ORANGE = "#FE611F";
export const BRAND_GOLD = "#F4BF54";
`;

writeFileSync(TARGET, out, "utf8");
console.log(`Wrote ${TARGET} (${out.length} bytes, svg ${svg.length})`);

/* ── The same mark as base64 PNG, for the PDF ──────────────────────
   jsPDF cannot draw SVG, and the PDF is generated in the browser at
   booking time and posted to n8n — so it cannot depend on fetching an
   image either. Inlining the bytes is what makes the PDF work with no
   network at all.                                                    */

const PNG = "public/brand/fidato-hotels.png";
const PNG_TARGET = "src/assets/brand/logoPng.ts";

const png = readFileSync(PNG);
const pngOut = `/* ⚠️ GENERATED by scripts/build-logo.mjs from ${PNG}.
   Do not hand-edit.

   The wordmark as a base64 PNG, for jsPDF — which cannot draw SVG, and
   which runs at booking time where a network fetch may not be
   available. ${png.length} bytes. */

export const FIDATO_LOGO_PNG = "data:image/png;base64,${png.toString("base64")}";

/** Intrinsic size, so callers scale rather than guess an aspect ratio. */
export const FIDATO_LOGO_PNG_SIZE = { width: 440, height: 124 };
`;

writeFileSync(PNG_TARGET, pngOut, "utf8");
console.log(`Wrote ${PNG_TARGET} (${png.length} byte png)`);
