/* ═══════════════════════════════════════════════════════════════
   REAL PROPERTY DATA — Fidato partner portfolio

   Extracted from the 32 official fact sheets in
   D:\Fidato Assets\Hotel Fact Sheets. Names, cities, room counts,
   room mixes, features, amenities and landmark distances are the
   property's actual published details. Commercial figures
   (commission, rates) are simulated for Phase 1.

   Generated — do not hand-edit. Re-run the extractor to refresh.
   ═══════════════════════════════════════════════════════════════ */

export interface SeedRoomType {
  name: string;
  count: number;
}

export interface SeedDistance {
  label: string;
  km: number;
}

export interface SeedHotel {
  id: string;
  name: string;
  shortName: string;
  city: string;
  state: string;
  address: string;
  category: string;
  status: string;
  starRating: number;
  totalRooms: number;
  description: string;
  roomMix: string[];
  roomTypes: SeedRoomType[];
  features: string[];
  facilities: string[];
  amenities: string[];
  thingsToDo: string[];
  distances: SeedDistance[];
  commissionPercent: number;
}

export const SEED_HOTELS: SeedHotel[] = [
  {
    id: "htl-agra-agra-hotel-taj-pearl",
    name: "Agra Hotel Taj Pearl",
    shortName: "Agra Hotel Taj Pearl",
    city: "Agra",
    state: "Uttar Pradesh",
    address: "Agra, Uttar Pradesh",
    category: "business",
    status: "active",
    starRating: 3,
    totalRooms: 24,
    description: "A beautiful 3 star boutique hotel inspired by the beauty of simplicity and warm hospitality, under the management of Three Fernz Hospitality. Strategically located in close proximity to Taj Mahal, Railway Station, and Airport. Hotel Taj Pearl is set to deliver an inviting and seamless experience to leisure and business travelers visiting Agra. The hotel is also a perfect place for weddings and events alike for localities for its large banquet spaces. The hotel promises the highest standard of hospitality and services across all areas.",
    roomMix: ["Deluxe Room - 14 Rooms", "Super Deluxe Room - 8 Rooms", "Suite - 2 Rooms"],
    roomTypes: [{ name: "Deluxe Room", count: 14 }, { name: "Super Deluxe Room", count: 8 }, { name: "Suite", count: 2 }],
    features: ["Public Restrooms", "Power Backup", "Free parking", "Wireless Internet", "Television", "24-hour Room Service"],
    facilities: ["WiFi", "Concierge Service", "laundry", "Public Restrooms"],
    amenities: ["Dining Area", "Swimming Pool", "24-hour Room Service", "Parking"],
    thingsToDo: ["Taj Mahal", "Agra Fort", "Sikandra", "Fatehpur Sikri"],
    distances: [{ label: "Airport", km: 10.3 }, { label: "Landmark", km: 7.8 }, { label: "Bus Stand", km: 7.0 }, { label: "Taj Mahal", km: 5.0 }, { label: "Agra Fort", km: 6.0 }, { label: "Sikandra", km: 18.0 }, { label: "Fatehpur Sikri", km: 43.0 }],
    commissionPercent: 12,
  },
  {
    id: "htl-agra-clarks-shiraz",
    name: "Clarks Shiraz",
    shortName: "Clarks Shiraz",
    city: "Agra",
    state: "Uttar Pradesh",
    address: "Agra, Uttar Pradesh",
    category: "heritage",
    status: "active",
    starRating: 5,
    totalRooms: 236,
    description: "Clarks Shiraz, Agra, is a five-star luxury hotel which combines business with pleasure, style with substance, form with function. Located 2 km. from the Taj Mahal, in the heart of Agra, and yet free from its din and bustle, The Clarks Shiraz is just 7 km. from the Airport and 3 km. from the Railway Station. Overlooking the Taj and Agra Fort, Hotel Clarks Shiraz has been synonymous with exceptional hospitality for the last five decades. The hotel has the honour of serving a number of distinguished guests. This 5-star Taj facing rooms in the city. The hotel offers an array of delectable cuisine, ranging from Mughlai, Continental, and Chinese to a variety of exotic beverages, at its various restaurants and Coffee Shop. Clarks Shiraz caters with utmost efficiency to the multifarious needs of the corporate travelers as well as the business clientele. 20 DELUXE ROOMS 14 DELUXE ROOMS (TAJ FACIN",
    roomMix: ["Deluxe Rooms - 20 Rooms", "Deluxe Rooms (taj Facing) - 14 Rooms", "Superior Rooms - 99 Rooms", "Premium Rooms - 100 Rooms", "Suites Room - 3 Rooms"],
    roomTypes: [{ name: "Deluxe Rooms", count: 20 }, { name: "Deluxe Rooms (taj Facing)", count: 14 }, { name: "Superior Rooms", count: 99 }, { name: "Premium Rooms", count: 100 }, { name: "Suites Room", count: 3 }],
    features: ["Buffet Breakfast", "Tea/Coffee Maker", "Free Wi-Fi", "Equipped With Mini Bar & Television", "Personal Safes", "Laundry Service", "Hair Dryer", "Banquet, Restaurant & Cafe", "Valet Parking", "Spa"],
    facilities: [],
    amenities: ["Snehnaz Hall", "Entatainment Room", "Health Club", "Swiming Pool"],
    thingsToDo: ["Taj Mahal", "Agra Fort", "Sheesh Mahal", "Siddi Sayed Mosque"],
    distances: [{ label: "Agra Airport", km: 9.2 }, { label: "Agra Fort", km: 3.8 }, { label: "Idgah Bus Stand", km: 3.6 }, { label: "Taj Mahal", km: 3.1 }, { label: "Agra Fort", km: 3.4 }, { label: "Sheesh Mahal", km: 2.2 }, { label: "Mehtab Bagh", km: 3.2 }],
    commissionPercent: 10,
  },
  {
    id: "htl-akkalkot-5-elements-by-fidato-hotels",
    name: "5 Elements by Fidato Hotels",
    shortName: "5 Elements by Fidato Hotels",
    city: "Akkalkot",
    state: "Maharashtra",
    address: "Akkalkot, Maharashtra",
    category: "business",
    status: "active",
    starRating: 3,
    totalRooms: 17,
    description: "5 Elements by Fidato Hotels, Akkalkot is a contemporary hotel designed to offer a comfortable and peaceful stay for pilgrims, families, and business travelers visiting the holy town of Akkalkot. Conveniently located near the revered Shri Swami Samarth Temple, the hotel combines modern amenities with warm hospitality, ensuring a relaxing and memorable experience. Whether you're visiting for spiritual purposes or a short getaway, 5 Elements by Fidato Hotels provides well- appointed accommodations, attentive service, and easy access to the town's major attractions.",
    roomMix: ["Deluxe Rooms - 3 Rooms", "Superior Rooms - 10 Rooms", "Executive Rooms - 3 Rooms", "Family Room - 1 Rooms"],
    roomTypes: [{ name: "Deluxe Rooms", count: 3 }, { name: "Superior Rooms", count: 10 }, { name: "Executive Rooms", count: 3 }, { name: "Family Room", count: 1 }],
    features: ["Buffet Breakfast", "Banquet Hall", "Housekeeping", "24/7 Hour Reception", "Tea / Coffee Maker", "Furnished Rooms", "Wi-Fi"],
    facilities: ["Buffet Breakfast", "Pure Veg Restuarant", "Banquet", "Free WiFi"],
    amenities: ["Tea / Coffee Maker", "Smart Television", "24/7 Front Desk", "Parking"],
    thingsToDo: ["Shree Vatavriksha Swami Samarth", "Shivpuri Mandir", "New Palace Museum", "Guru Mandir", "Mandir"],
    distances: [{ label: "Landmark", km: 38.0 }, { label: "Solapur Airport Akkalkot Railway Akkalkot Bus St", km: 9.1 }, { label: "Solapur Airport Akkalkot Railway Akkalkot Bus St", km: 2.9 }, { label: "Landmark", km: 1.2 }, { label: "New Palace Museum", km: 2.1 }, { label: "Shree Vatavriksha Swami Samarth Mandir", km: 2.8 }, { label: "Guru Mandir", km: 3.6 }],
    commissionPercent: 15,
  },
  {
    id: "htl-alibaug-silvanus",
    name: "Silvanus",
    shortName: "Silvanus",
    city: "Alibaug",
    state: "Maharashtra",
    address: "Alibaug, Maharashtra",
    category: "resort",
    status: "active",
    starRating: 4,
    totalRooms: 60,
    description: "Silvanus Forest Retreat- Escape to our unique oasis nestled in the lush greens of Alibaug. When you think of Alibaug, the first thing that comes to mind is undoubtedly its pristine beaches. Discover luxury at our resort near Revdanda Beach, boasting 60 spacious suites surrounded by serene landscapes. Immerse in poolside tranquility, marvel at breathtaking sunsets, and wake up to birdsong. Our multi-cuisine restaurant offers a gastronomic journey, complemented by well-crafted cocktails at our bar. Beyond vacations, our resort transforms into an ideal venue for destination weddings and events in Alibaug. Let us host your special occasions, creating unique memories. Silvanus Forest Retreat extends a warm invitation to rediscover your love for nature and experience the epitome of luxury in Alibaug.",
    roomMix: ["Deluxe Cottage - 34 Rooms", "Premium Villa - 18 Rooms", "Family Suite - 8 Rooms"],
    roomTypes: [{ name: "Deluxe Cottage", count: 34 }, { name: "Premium Villa", count: 18 }, { name: "Family Suite", count: 8 }],
    features: ["Swimming Pool", "BBQ facilities", "Power Backup", "24-hour Room Service", "Kids Play Area"],
    facilities: ["Swimming Pool", "Concierge Service", "Banquet", "24-hour Security"],
    amenities: ["Power Backup", "BBQ Facilities"],
    thingsToDo: ["Korlai Fort", "Akshi Beach", "Shri Ballaleshwar Ashtavinayaka"],
    distances: [{ label: "Ferry", km: 15.0 }, { label: "Landmark", km: 15.0 }, { label: "Bus Stand", km: 15.0 }, { label: "Landmark", km: 3.0 }, { label: "Korlai Fort", km: 9.0 }, { label: "Akshi Beach", km: 9.0 }, { label: "Shri Ballaleshwar Ashtavinayaka", km: 3.3 }],
    commissionPercent: 12,
  },
  {
    id: "htl-bengaluru-bngv-the-grandeur-hotel-banquets",
    name: "Bngv THE Grandeur Hotel & Banquets",
    shortName: "Bngv THE Grandeur Hotel & Ba",
    city: "Bengaluru",
    state: "Karnataka",
    address: "Bengaluru, Karnataka",
    category: "business",
    status: "active",
    starRating: 3,
    totalRooms: 44,
    description: "44 Keys, Contemporary designed guest rooms, ideally quipped for business, leisure and transit travellers. Located in the heart of Bengaluru city, Koramangala. Option of flexible meeting spaces that can accommodate up to 1200 guests including the state of the art Boardroom. Wide variety of Food & Bevarage outlets to choose from. Huge variety of Recreational Facilities to break away from a hectic routine. 8 PREMIER KING ROOMS : 500 Sq. ft. 8 PREMIER TWIN ROOMS : 500 Sq. ft. 6 PREMIER SUITE ROOMS : 750 Sq. ft. 22 DELUXE ROOMS",
    roomMix: ["500 Sq. Ft. Premier King Rooms - 8 Rooms", "Premier Twin Rooms : 500 Sq. Ft. - 8 Rooms", "Premier Suite Rooms : 750 Sq. Ft. - 6 Rooms", "Deluxe Rooms - 22 Rooms"],
    roomTypes: [{ name: "500 Sq. Ft. Premier King Rooms", count: 8 }, { name: "Premier Twin Rooms : 500 Sq. Ft.", count: 8 }, { name: "Premier Suite Rooms : 750 Sq. Ft.", count: 6 }, { name: "Deluxe Rooms", count: 22 }],
    features: ["Breakfast", "Tea/Coffee Maker", "Free Wi-Fi", "Television", "Laundry Service", "Hair Dryer", "Banquet, Restaurant & Cafe", "Spa"],
    facilities: [],
    amenities: ["Bar & Restaurant", "Spa", "Saloon"],
    thingsToDo: ["Cubbon Park", "Lalbagh Botanical Garden", "Tipu Sultan's Summer Palace", "Bannerghatta Biological Park"],
    distances: [{ label: "Bengaluru Airport", km: 40.0 }, { label: "City", km: 9.9 }, { label: "Tipu Sultan's Summer Palace", km: 8.4 }, { label: "Bannerghatta Biological Park", km: 19.0 }, { label: "Mg", km: 3.0 }, { label: "Cubbon Park", km: 7.9 }, { label: "UB City", km: 4.5 }],
    commissionPercent: 13,
  },
  {
    id: "htl-bhopal-safal-retreat",
    name: "Safal Retreat",
    shortName: "Safal Retreat",
    city: "Bhopal",
    state: "Madhya Pradesh",
    address: "Bhopal, Madhya Pradesh",
    category: "resort",
    status: "active",
    starRating: 4,
    totalRooms: 30,
    description: "Stipulated in a captivating and opulent ambience, bundling a green estate and alluring with the magical charm of its own. The Safal Retreat, located in Bhopal's lush green area of Van Vihar, brings up an amazing experience for its Guests. A perfect place to enjoy your stay with beautifully crafted rooms, special days. 18 PREMIUM ROOMS 10 PREMIUM CLUB ROOMS 2 EXOTIC ROOMS",
    roomMix: ["Premium Rooms - 18 Rooms", "Premium Club Rooms - 10 Rooms", "Exotic Rooms - 2 Rooms"],
    roomTypes: [{ name: "Premium Rooms", count: 18 }, { name: "Premium Club Rooms", count: 10 }, { name: "Exotic Rooms", count: 2 }],
    features: ["Buffet Breakfast", "Tea/Coffee Maker", "High Speed Wi-Fi", "Equipped With Mini Bar & Television", "Laundry service", "Hair Dryer", "Banquet, Restaurant & Cafe", "Valet parking"],
    facilities: [],
    amenities: ["BANQUET HALL-7000sq.ft.", "LAWN-25000sq.ft.", "Business Center"],
    thingsToDo: ["Van Vihar National Park Bhopal", "Madhya Pradesh Tribal Museum", "Upper Lake View Point", "Taj Ul Masajid"],
    distances: [{ label: "Airport", km: 17.4 }, { label: "Habibganj", km: 9.5 }, { label: "New Market", km: 4.4 }, { label: "Center", km: 6.0 }, { label: "Van Vihar National Park", km: 1.5 }, { label: "Taj Ul Masajid", km: 7.6 }, { label: "Kerwa Dam Lake", km: 11.2 }],
    commissionPercent: 12,
  },
  {
    id: "htl-daman-devka-beach-resort",
    name: "Devka Beach Resort",
    shortName: "Devka Beach Resort",
    city: "Daman",
    state: "Daman & Diu",
    address: "and Nagar Haveli and Daman and Diu 396210",
    category: "beach",
    status: "active",
    starRating: 3,
    totalRooms: 100,
    description: "Welcome to Devka Beach Resort, We are the ideal vacation for peaceful beaches, beautiful vistas, and delectable food, and we're close to Devka Beach in Daman. One of the most luxurious resorts in Daman, Devka Beach Resort has spacious accommodations, an elegant café called Hola Amigos, a spectacular pub and an open-air bar and lounge, making it the perfect place for a leisurely weekend getaway with friends and family.The place gives the feeling of being on an island far from the rigors of worldly life, but with all the amenities under one roof, including Chicurry - The multicuisine dining restaurant, and Churning Wheels - a paradise for vegetarian delicacies.",
    roomMix: ["Standard Room - 52 Rooms", "Deluxe Sea View - 34 Rooms", "Suite - 14 Rooms"],
    roomTypes: [{ name: "Standard Room", count: 52 }, { name: "Deluxe Sea View", count: 34 }, { name: "Suite", count: 14 }],
    features: ["Air Conditioner", "Mini Bar", "Tea/Coffee Maker", "Wireless Internet", "Closet / Wardrobe", "Television"],
    facilities: ["WiFi", "Swimming Pool", "laudary", "24/7 Room Service"],
    amenities: ["Banquet Hall", "Parking", "Conference Hall", "Dining Area"],
    thingsToDo: ["Moti Daman Fort", "Church Of Our Lady Of Sea", "Mirasol Lake Garden", "Devka Amusement Park"],
    distances: [{ label: "Landmark", km: 12.0 }, { label: "Bus Stand", km: 18.9 }, { label: "Moti Daman Fort Church Of Our", km: 7.6 }, { label: "Lady Of Sea", km: 5.5 }, { label: "Mirasol Lake Garden", km: 2.2 }, { label: "Devka Amusement Park", km: 1.6 }, { label: "Dominican Monastery", km: 7.7 }],
    commissionPercent: 13,
  },
  {
    id: "htl-durgapur-peerless-hotel",
    name: "Peerless Hotel",
    shortName: "Peerless Hotel",
    city: "Durgapur",
    state: "West Bengal",
    address: "Durgapur, West Bengal",
    category: "business",
    status: "active",
    starRating: 4,
    totalRooms: 83,
    description: "The Peerless Inn Durgapur is the finest hotel in the steel city of India, As a 3-star classified business hotel, the property offers comfort with warm service and hospitality to every business traveller. The hotel features 108 premium and deluxe rooms with cosy interiors which makes our guests feel blissfully comfortable. A full seamless and worry-free. The banquet halls are fitted with the latest audio-visual equipment and advance audio system, making it an ideal venue for upto 250 guests. In addition to this, the property also has an upper and lower lawn area with a capacity to accommodate 4000 guests, which makes this a perfect venue for conference, weddings and exhibition. 6 DELUXE ROOMS 225: Sq. Ft 45 PREMIUM ROOMS: 275 Sq. ft. 22 EXECUTIVE PREMIUM 9 JUNIOR SUITES: 350 Sq. ft. 1 PRESIDENTIAL SUITES: 550 Sq. ft.",
    roomMix: ["Deluxe Rooms 225: Sq. Ft - 6 Rooms", "275 Sq. Ft. Premium Rooms - 45 Rooms", "Executive Premium 325 Sq. Ft. - 22 Rooms", "Junior Suites: 350 Sq. Ft. - 9 Rooms", "Presidential Suites: 550 Sq. Ft. - 1 Rooms"],
    roomTypes: [{ name: "Deluxe Rooms 225: Sq. Ft", count: 6 }, { name: "275 Sq. Ft. Premium Rooms", count: 45 }, { name: "Executive Premium 325 Sq. Ft.", count: 22 }, { name: "Junior Suites: 350 Sq. Ft.", count: 9 }, { name: "Presidential Suites: 550 Sq. Ft.", count: 1 }],
    features: ["Buffet Breakfast", "Tea/Coffee Maker", "Free Wi-Fi", "Equipped With Mini Bar & Television", "Personal Safes", "Laundry Service", "Hair Dryer", "Banquet, Restaurant & Cafe", "Valet Parking", "Spa"],
    facilities: [],
    amenities: ["Gym", "High Octane Bar", "Conclave Banquet Hall"],
    thingsToDo: ["Garh Jungle", "Durgapur Steel Plant", "Durgapur Barrage", "Kumarmanglam Park"],
    distances: [{ label: "Kazi narzul Islam Airport", km: 20.0 }, { label: "Durgapur", km: 9.0 }, { label: "Bhabani Pathak Tila", km: 2.0 }, { label: "Drgapur Steel Plant", km: 6.5 }, { label: "Kumarmanglam Park", km: 3.0 }, { label: "garh Jungle", km: 25.0 }],
    commissionPercent: 11,
  },
  {
    id: "htl-goa-turtle-beach-resort",
    name: "Turtle Beach Resort",
    shortName: "Turtle Beach Resort",
    city: "Goa",
    state: "Goa",
    address: "Goa, Goa",
    category: "beach",
    status: "active",
    starRating: 4,
    totalRooms: 111,
    description: "The hotel welcomes you with its fresh bold interiors, as well as crisp and clean rooms, and delights you with its unbeatable value and reliable safety standards. Here, friendly smiles and a lively environment go hand in hand with professional service. A hotel that is young at heart, Morjim lets you be yourself. It offers 111 smart rooms, including one executive suite; a multi-cuisine restaurant, Clever Fox Café, complemented by a bar, Tipsy Fox. Banquet",
    roomMix: ["Executive Suite Rooms - 1 Rooms", "Deluxe Rooms - 48 Rooms", "Executive Rooms - 20 Rooms", "Superior Rooms - 42 Rooms"],
    roomTypes: [{ name: "Executive Suite Rooms", count: 1 }, { name: "Deluxe Rooms", count: 48 }, { name: "Executive Rooms", count: 20 }, { name: "Superior Rooms", count: 42 }],
    features: ["Buffet Breakfast", "Tea/Coffee Maker", "Free Wi-Fi", "Equipped With Mini Bar & Television", "Personal Safes", "Laundry Service", "Hair Dryer", "Banquet, Restaurant & Cafe", "Valet Parking", "Spa"],
    facilities: ["becomes the first choice for value conscious travelers."],
    amenities: ["Swimming Pool", "Clever Fox Cafe", "Fitness Centre", "Wellness Centre"],
    thingsToDo: ["Morjim Beach", "Aguada Fort", "Tortoise Beach", "Anjuna Beach"],
    distances: [{ label: "Dabolim Airport", km: 50.0 }, { label: "Thivim", km: 19.0 }, { label: "Baga Beach", km: 6.7 }, { label: "Morjim Beach", km: 3.0 }, { label: "Aguada Fort", km: 1.9 }, { label: "Tortoise Beach", km: 1.4 }, { label: "Arambol Beach", km: 6.5 }],
    commissionPercent: 12,
  },
  {
    id: "htl-goa-de-mandarin-hotel",
    name: "De Mandarin Hotel",
    shortName: "De Mandarin Hotel",
    city: "Goa",
    state: "Goa",
    address: "Goa, Goa",
    category: "business",
    status: "active",
    starRating: 3,
    totalRooms: 58,
    description: "De Mandarin focuses on personalised experiences and outstanding service. Our carefully chosen location in Candolim allows guests to indulge in the quiet respite of a Goan village while staying within easy reach of all the exciting activities the north Goa beach belt is famous for. Spoil yourself in the comfort of our luxurious rooms, designed to offer amenities that are electronically controlled as well as opulent. Sample a variety of flavours in the evening sipping premium spirits and the best cocktails in our charming bar.",
    roomMix: ["Deluxe Room - 36 Rooms", "Executive Room - 16 Rooms", "Suite - 6 Rooms"],
    roomTypes: [{ name: "Deluxe Room", count: 36 }, { name: "Executive Room", count: 16 }, { name: "Suite", count: 6 }],
    features: ["Air Conditioner", "Mini Bar", "Tea/Coffee Maker", "Wireless Internet", "Closet / Wardrobe", "Television", "Complimentary Breakfast"],
    facilities: ["WiFi", "Concierge Service", "laundry", "Babysitting Services"],
    amenities: ["Complimentary Breakfast", "Swimming Pool", "Safety deposit locker", "Luxury toiletries"],
    thingsToDo: ["Basilica of Bom Jesus", "Konkan Explorers", "Candolim Beach", "Deltin Royale"],
    distances: [{ label: "Airport", km: 37.0 }, { label: "Landmark", km: 20.7 }, { label: "Basilica of Bom Jesus", km: 18.5 }, { label: "Konkan Explorers Candolim Beach", km: 17.4 }, { label: "Landmark", km: 1.4 }, { label: "Deltin Royale", km: 11.4 }],
    commissionPercent: 13,
  },
  {
    id: "htl-goa-de-mandarin-resort",
    name: "De Mandarin Resort",
    shortName: "De Mandarin Resort",
    city: "Goa",
    state: "Goa",
    address: "Goa, Goa",
    category: "resort",
    status: "onboarding",
    starRating: 4,
    totalRooms: 23,
    description: "Escape to De Mandarin Beach Resort, a captivating coastal haven on Candolim's sandy shores in North Goa. Spanning 3.3 acres, this enchanting beachfront retreat promises awe-inspiring sunsets. Immerse yourself in Goa's vibrant ambiance, with direct access to candolim beach from the property and with easy access to acclaimed restaurants, lively bars, and pulsating nightspots. Discover our 23 meticulously crafted suites and villas, where elegance meets comfort in perfect harmony. At De Mandarin Beach Resort, we create extraordinary Goan memories that linger long after you depart this idyllic coastal paradise.",
    roomMix: ["Garden View Room - 14 Rooms", "Pool View Room - 7 Rooms", "Suite - 2 Rooms"],
    roomTypes: [{ name: "Garden View Room", count: 14 }, { name: "Pool View Room", count: 7 }, { name: "Suite", count: 2 }],
    features: ["Air Conditioner", "Mini Bar", "Tea/Coffee Maker", "Wireless Internet", "Closet / Wardrobe", "Television", "Complimentary Breakfast"],
    facilities: ["WiFi", "Concierge Service", "laundry", "Babysitting Services"],
    amenities: ["Swimming Pool", "Open Garden", "Luxury toiletries"],
    thingsToDo: ["Basilica of Bom Jesus", "Konkan Explorers", "Candolim Beach", "Deltin Royale"],
    distances: [{ label: "Airport", km: 37.0 }, { label: "Landmark", km: 20.7 }, { label: "Basilica of Bom Jesus", km: 18.5 }, { label: "Konkan Explorers Candolim Beach", km: 17.4 }, { label: "Landmark", km: 1.4 }, { label: "Deltin Royale", km: 11.4 }],
    commissionPercent: 13,
  },
  {
    id: "htl-hyderabad-peerless-inn",
    name: "Peerless Inn",
    shortName: "Peerless Inn",
    city: "Hyderabad",
    state: "Telangana",
    address: "Hyderabad, Telangana",
    category: "business",
    status: "active",
    starRating: 4,
    totalRooms: 65,
    description: "The Peerless Inn, Hyderabad welcomes you to the City of Nawabs. A three-star deluxe hotel, where we offer top class facilities and services in order to attain the highest level of customer satisfaction. A full- service hotel with 65 rooms with contemporary sophistication. The rooms offer exquisite interior with modern finish and amenities for a modern traveller. For the corporate traveler, a compact Business Centre and Banquet with Wi-Fi makes the hotel ideal for your business. The property, offers finest cuisine at Pavilion - a Multi cuisine Restaurant specializing in Hyderabadi (Andhra) food besides Chinese, Indian and Continental which are its continuing delicacies. 47 SUPERIOR ROOM: 300 Sq. ft. 18 EXECUTIVE ROOM: 530 Sq. ft.",
    roomMix: ["Superior Room: 300 Sq. Ft. - 47 Rooms", "Executive Room: 530 Sq. Ft. - 18 Rooms"],
    roomTypes: [{ name: "Superior Room: 300 Sq. Ft.", count: 47 }, { name: "Executive Room: 530 Sq. Ft.", count: 18 }],
    features: ["Breakfast", "Free Wi-Fi", "Laundry & Hair Dryer", "Television, Safety Lockers & Telephone", "Mini Bar & Valet parking", "Private Vehicle Parking", "Cubical Glass Bathroom & Car Rental", "Complimentary Water Bottle", "Female Traveler Room / Floor", "Swimming Pool"],
    facilities: [],
    amenities: ["Buffet", "Gym"],
    thingsToDo: ["Charminar", "Golconda Fort", "Salar Jung Museum"],
    distances: [{ label: "Hyderabad Airport", km: 32.0 }, { label: "Hyderabad", km: 8.0 }, { label: "Charminar", km: 19.0 }, { label: "Golconda Fort", km: 10.0 }, { label: "Birla Mandir", km: 16.0 }, { label: "Salar Jung Museum", km: 20.0 }],
    commissionPercent: 11,
  },
  {
    id: "htl-indore-winway",
    name: "Winway",
    shortName: "Winway",
    city: "Indore",
    state: "Madhya Pradesh",
    address: "Indore, Madhya Pradesh",
    category: "business",
    status: "active",
    starRating: 3,
    totalRooms: 38,
    description: "Hotel winway is an elite & exquisite business hotel that reflects the great hospitality of Malwa & offers world class amenities & services to give a royal welcome to one and all. It is enjoying a privileged location, situated in the heart of the commercial and education hub of Madhya Pradesh, Indore. Merely 20 mins. drive from the airport and offers easy access to all modes of travel. Just blocks away from Central Mall on R.N.T. Marg, it boasts of enticing interiors, a classy appeal and always happy to help 38 LUXURY ROOMS STANDARD ROOMS: 252 Sq. ft. DELUXE ROOMS: 290 Sq. ft. JUNIOR SUITES: 300 Sq. ft. PRESIDENTIAL: 714 Sq. ft.",
    roomMix: ["Luxury Rooms Standard Rooms: 252 Sq. Ft. 290 Sq. Ft. Deluxe Rooms Junior Suites: 300 Sq. Ft. Presidential: 714 Sq. Ft. - 38 Rooms"],
    roomTypes: [{ name: "Luxury Rooms Standard Rooms: 252 Sq. Ft. 290 Sq. Ft. Deluxe Rooms Junior Suites: 300 Sq. Ft. Presidential: 714 Sq. Ft.", count: 38 }],
    features: ["Buffet Breakfast", "Tea/Coffee Maker", "Free Wi-Fi", "Equipped With Mini Bar & Television", "Personal Safes", "Laundry Service", "Hair Dryer", "Banquet, Restaurant & Cafe", "Valet Parking", "Spa"],
    facilities: [],
    amenities: ["Al-fresco", "The Deck", "Tiffin", "Food"],
    thingsToDo: ["Central Museum", "Kanch Mandir"],
    distances: [{ label: "Indore Airport", km: 10.0 }, { label: "Indore", km: 1.5 }, { label: "Wildlife Sanctuary", km: 12.0 }, { label: "Palace", km: 2.5 }, { label: "Kanch Mandir", km: 2.9 }, { label: "Central Museum", km: 2.0 }, { label: "Kamla Nehru Park", km: 2.2 }],
    commissionPercent: 13,
  },
  {
    id: "htl-jaipur-fiori",
    name: "Fiori",
    shortName: "Fiori",
    city: "Jaipur",
    state: "Rajasthan",
    address: "Jaipur, Rajasthan",
    category: "business",
    status: "active",
    starRating: 4,
    totalRooms: 57,
    description: "Hotel FIORI provides excellent banquet facilities for Weddings, Reception, Theme Parties, Anniversaries, Reunions, Business Meetings, Conferences & other Gatherings. Hotel FIORI is an ideal spot for any get together with 2 Large Banquets. Our dedicated conference hall for a perfect corporate function and a perfect dining area for a perfect Board Meetings. Parking will never be a problem for you as we have ample parking space of up to 100 cars. Select your package from our exclusive banquet menu and our professional staff will help you to design and plan your event. Wedding/ Engagement are our speciality, accommodating up to 2000 guests and making your dream weddings come true",
    roomMix: ["Deluxe Room - 34 Rooms", "Executive Room - 17 Rooms", "Suite - 6 Rooms"],
    roomTypes: [{ name: "Deluxe Room", count: 34 }, { name: "Executive Room", count: 17 }, { name: "Suite", count: 6 }],
    features: ["Air Conditioner", "BBQ facilities", "Key card access", "Wireless Internet", "Television", "Non-smoking rooms"],
    facilities: ["WiFi", "Concierge Service", "Banquet", "24-hour Security"],
    amenities: ["Bike Tour", "Walking tours"],
    thingsToDo: ["Statue Circle", "Birla Planetarium", "Museum Of Indology", "Nahargarh Fort Palace"],
    distances: [{ label: "Airport", km: 9.0 }, { label: "Landmark", km: 7.7 }, { label: "Bus Stand", km: 10.0 }, { label: "Statue Circle", km: 7.0 }, { label: "Birla Planetarium", km: 7.0 }, { label: "Museum Of Indology", km: 8.0 }, { label: "Nahargarh Fort Palace", km: 9.0 }],
    commissionPercent: 12,
  },
  {
    id: "htl-jaipur-khandela-haveli",
    name: "Khandela Haveli",
    shortName: "Khandela Haveli",
    city: "Jaipur",
    state: "Rajasthan",
    address: "Jaipur, Rajasthan",
    category: "heritage",
    status: "active",
    starRating: 4,
    totalRooms: 28,
    description: "Khandela is an ancient town (more than 2000 years old) and was ruled by various dynasties of the Shekhawati with Khandela as its capital from 1538 - 1615 AD and the descendents ruled the state till Indian independence. The present owners are the 17th and 18th Generation of Raja Raisal. The descendants of Raja Raisal during their rule also developed the region of Shekhawati to make it a internationally known tourist destination specially for its architecture of Havelis (residence of the Elite), castles & forts. Here in Khandela Haveli at Jaipur, we present the same form of architecture and frescos and offer our guests the traditional royal hospitality with modern comforts. 19 STANDARD ROOMS 9 SUITES",
    roomMix: ["Standard Rooms - 19 Rooms", "Suites - 9 Rooms"],
    roomTypes: [{ name: "Standard Rooms", count: 19 }, { name: "Suites", count: 9 }],
    features: ["Buffet Breakfast", "Free Wi-Fi", "Attached Washrooms", "Television, Safety Lockers & Telephone", "Luxurious Linens & Towels", "Laundry Service", "Private Vehicle Parking", "Car Rental", "Doctor On Call", "Swimming Pool"],
    facilities: ["Historical Photo Walks of the Haveli", "Terrace Swimming with Sunbathing Area", "Currency Exchange", "Full Air Conditioned Restaurant Cum Bar", "Other Facilities", "Gala Dinner", "Cultural Programme", "Photo/movie Shoot"],
    amenities: [],
    thingsToDo: [],
    distances: [{ label: "Jaipur Airport", km: 13.4 }, { label: "Jaipur", km: 2.0 }, { label: "Hawa Mahal", km: 5.2 }, { label: "Birla Temple", km: 7.0 }, { label: "Nahargarh Fort", km: 4.4 }, { label: "City Palace", km: 4.0 }, { label: "Jal Mahal", km: 7.6 }],
    commissionPercent: 12,
  },
  {
    id: "htl-kolkata-peerless-inn",
    name: "Peerless Inn",
    shortName: "Peerless Inn",
    city: "Kolkata",
    state: "West Bengal",
    address: "Kolkata, West Bengal",
    category: "business",
    status: "active",
    starRating: 4,
    totalRooms: 168,
    description: "With the timeless traditions of hospitality, The Peerless Inn Kolkata, welcome you with warmth and charm. Located at heart of the city, in Chowringhee, The Peerless Inn, is situated at the perfect location for business and relaxation. An upscale 4 star hotel, this business hotel offers its travellers every possible convenience with premium accommodation, meeting and conference room, fitness centre. All 168 rooms and suites of the hotel provide its guests with the pleasure of blissful comfort. Here, a full range of conferencing and banqueting facilities are managed by expert professionals who keep your event seamless and worry-free. The banquet halls are fitted with the latest audio visual equipment and advance audio system, making it ideal venue for upto 350 guests. For corporate travellers we offer a state-of-art business centre equipped with wifi access throughout the hotel. 60 SUPERIO",
    roomMix: ["Superior Room: 255 Sq. Ft. - 60 Rooms", "Premiere Room: 250 Sq. Ft. - 44 Rooms", "Ex. Premiere Room: 255 Sq. Ft. - 3 Rooms", "Deluxe Room: 255 Sq. Ft. - 35 Rooms", "Suite Room: 451 Sq. Ft. - 15 Rooms", "Chowringhee Suite - 11 Rooms"],
    roomTypes: [{ name: "Superior Room: 255 Sq. Ft.", count: 60 }, { name: "Premiere Room: 250 Sq. Ft.", count: 44 }, { name: "Ex. Premiere Room: 255 Sq. Ft.", count: 3 }, { name: "Deluxe Room: 255 Sq. Ft.", count: 35 }, { name: "Suite Room: 451 Sq. Ft.", count: 15 }, { name: "Chowringhee Suite", count: 11 }],
    features: ["Breakfast", "Free Wi-Fi", "Laundry & Hair Dryer", "Television, Safety Lockers & Telephone", "Mini Bar & Valet parking", "Private Vehicle Parking", "Cubical Glass Bathroom & Car Rental", "Complimentary Water Bottle", "Female Traveler Room / Floor", "Swimming Pool"],
    facilities: [],
    amenities: [],
    thingsToDo: [],
    distances: [{ label: "Kolkata Airport", km: 24.0 }, { label: "Kolkata", km: 2.5 }, { label: "Victoria Memorial", km: 3.0 }, { label: "Howrah Bridge", km: 3.7 }, { label: "Belur Math", km: 9.5 }, { label: "Indian Museum", km: 1.3 }, { label: "Dakshineswar Kali Temple", km: 14.0 }],
    commissionPercent: 11,
  },
  {
    id: "htl-kolkata-northin-hotel",
    name: "Northin Hotel",
    shortName: "Northin Hotel",
    city: "Kolkata",
    state: "West Bengal",
    address: "176 PULIN AVENUE MALANCHA BELGHARI EXPRESS WAY KOLKATA -700081",
    category: "business",
    status: "paused",
    starRating: 3,
    totalRooms: 7,
    description: "Northin Hotel, Located just a few minutes away from Kolkata's Netaji Subhash Chandra Bose International Airport, offers a perfect blend of comfort, convenience, and luxury. Ideal for layovers, business, or leisure stays, the hotel provides modern amenities, including free Wi-Fi, a fitness center, swimming pool, and 24/7 room service. Guests can enjoy fine dining at Nourish, featuring international and authentic cuisine. With spacious meeting rooms, conference facilities, and an airport shuttle service, Northin ensures seamless connectivity and a premium experience near Kolkata's industrial hubs and Silicon Valley.",
    roomMix: ["Boutique Room - 5 Rooms", "Studio Suite - 2 Rooms"],
    roomTypes: [{ name: "Boutique Room", count: 5 }, { name: "Studio Suite", count: 2 }],
    features: ["24 Hrs Front Desk", "Events & Conferences", "On Site Parking", "High Speed Internet", "Indoor Swimming Pool", "Car Rental Desk"],
    facilities: ["On Site Parking", "Power Backup", "Free WiFi"],
    amenities: ["Car Rental Desk", "Banquet", "Indoor Swimming Pool"],
    thingsToDo: ["Eco-tourism Park", "Mother's Wax Museum", "Biswa Bangla Gate", "Eden Gardens"],
    distances: [{ label: "Dum Dum Junction", km: 7.0 }, { label: "Airport", km: 1.5 }, { label: "Maidan Park", km: 2.1 }, { label: "Durga Nagar Sports Club Ground", km: 2.5 }, { label: "G K Park", km: 3.2 }, { label: "Space Town Park", km: 3.5 }, { label: "Swimaji Park", km: 4.1 }],
    commissionPercent: 14,
  },
  {
    id: "htl-lonavala-hills-and-lakes",
    name: "Hills and Lakes",
    shortName: "Hills and Lakes",
    city: "Lonavala",
    state: "Maharashtra",
    address: "Lonavala, Maharashtra",
    category: "hill_station",
    status: "active",
    starRating: 4,
    totalRooms: 34,
    description: "A serene retreat in the heart of Lonavala, offering the perfect escape from the bustling cities of Mumbai and Pune. Immerse yourself in the tranquil embrace of nature, surrounded by lush greens and blessed with a cozy climate. Experience luxury and comfort with your family in the fully serviced executive apartments. 9 2BHK Terrance Suites with Private Access 25 2BHK Suites",
    roomMix: ["2BHK Suite - 25 Rooms", "2BHK Terrace Suite - 9 Rooms"],
    roomTypes: [{ name: "2BHK Suite", count: 25 }, { name: "2BHK Terrace Suite", count: 9 }],
    features: ["Free Wifi", "Indoor Games Room", "Gym", "Childrens Play Area", "Swimming Pool", "Elegant Clubhouse", "Banquet Hall", "24/7 Cctv"],
    facilities: ["WiFi", "Concierge Service", "laundry", "Private Cabana"],
    amenities: ["Dining Area", "Fitness centre", "Indoor Games Room", "Swimming Pool"],
    thingsToDo: ["Bhushi Dam", "Tiger's Leap", "Lonavala Lake", "Pawna Lake", "Popular destinations in Lonavala", "Lohagad Fort"],
    distances: [],
    commissionPercent: 13,
  },
  {
    id: "htl-mahabaleshwar-ayati-resort-and-spa",
    name: "Ayati Resort and Spa",
    shortName: "Ayati Resort and Spa",
    city: "Mahabaleshwar",
    state: "Maharashtra",
    address: "S No. 23/1/1, At Kaswand, Bhilar, Bhilar, Mahabaleshwar, Maharashtra, India, 412805.",
    category: "hill_station",
    status: "active",
    starRating: 4,
    totalRooms: 30,
    description: "Nestled in the hills of Kaswand, Bhilar, Ayati Resort & Spa offers a tranquil escape from the everyday. With 30 air-conditioned rooms featuring balconies that open to sweeping mountain views, it's a perfect blend of comfort and wilderness. Guests can lounge by the outdoor pool, unwind in the spa, and dine in one of the two restaurants- savoring delicious cuisine in scenic settings. With amenities like a children's pool, café, and free Wi-Fi, every stay is both relaxing and convenient. Whether you're planning a family getaway, romantic serenity, and warm hospitality.",
    roomMix: ["Valley View Room - 18 Rooms", "Premium Suite - 8 Rooms", "Villa - 4 Rooms"],
    roomTypes: [{ name: "Valley View Room", count: 18 }, { name: "Premium Suite", count: 8 }, { name: "Villa", count: 4 }],
    features: ["Swimming Pool", "Multicuisine Restaurant", "Indoor Kids Play Area", "Housekeeping", "24/7 Hour Reception", "24/7 Hour Security", "Bar (Opening Soon)", "SPA (Opening Soon)"],
    facilities: ["Swimming Pool", "Housekeeping", "Banquet"],
    amenities: ["Dining Area", "Kids Play Area", "24-hour Room Service", "Laundry"],
    thingsToDo: ["Table Land", "Mapro Garden", "Parsi Point", "Venna Lake"],
    distances: [{ label: "Airport -Pune", km: 120.0 }, { label: "Satara", km: 57.0 }, { label: "Table Land", km: 12.9 }, { label: "Mapro Garden", km: 7.5 }, { label: "Parsi Point", km: 7.8 }, { label: "Venna Lake", km: 19.5 }, { label: "Sydney Point", km: 11.2 }],
    commissionPercent: 12,
  },
  {
    id: "htl-mumbai-shalimar-hotel",
    name: "Shalimar Hotel",
    shortName: "Shalimar Hotel",
    city: "Mumbai",
    state: "Maharashtra",
    address: "August Kranti Rd, Kemps Corner, Malabar Hill, Mumbai, Maharashtra 400036",
    category: "business",
    status: "active",
    starRating: 4,
    totalRooms: 60,
    description: "Nestled in the heart of South Mumbai's elite residential district, The Shalimar Hotel is a four-star lifestyle property that exudes timeless elegance. Just a 45- minute drive from Mumbai's International Airport and conveniently located near the city's commercial hub and shopping district, our prime address offers unparalleled accessibility. Our bespoke guestrooms, including luxurious suites, are designed to cater to the discerning traveler. Each room is a harmonious blend of modern",
    roomMix: ["Superior Room - 34 Rooms", "Club Room - 18 Rooms", "Suite - 8 Rooms"],
    roomTypes: [{ name: "Superior Room", count: 34 }, { name: "Club Room", count: 18 }, { name: "Suite", count: 8 }],
    features: ["Free Wifi", "Free parking", "Fitness centre", "Spa and wellness centre", "Non-smoking rooms", "Tea/Coffee Maker", "Bar"],
    facilities: ["WiFi", "Concierge Service", "laundry", "Non-smoking rooms"],
    amenities: ["Hotel continues to redefine luxury hospitality.", "60 Rooms", "Studio Rooms :- 7 Rooms", "Zen Rooms :- 7 Rooms", "Smart Rooms :- 14 Rooms", "Comfort Rooms :- 24 Rooms", "Lifestyle Suites :- 8 Rooms"],
    thingsToDo: ["Breach Candy Garden", "August Kranti Maidan", "Hanging Gardens", "Chowpaty"],
    distances: [{ label: "Airport", km: 19.0 }, { label: "Mumbai Central", km: 2.0 }, { label: "Bus Stand", km: 8.5 }, { label: "Breach Candy Garden", km: 2.0 }, { label: "Hanging Gardens", km: 1.3 }, { label: "Chowpaty", km: 1.7 }],
    commissionPercent: 11,
  },
  {
    id: "htl-narkanda-hill-top-resort",
    name: "Hill Top Resort",
    shortName: "Hill Top Resort",
    city: "Narkanda",
    state: "Himachal Pradesh",
    address: "Patmani Point, NH22, Shillaru, Himachal Pradesh 171213",
    category: "hill_station",
    status: "active",
    starRating: 3,
    totalRooms: 15,
    description: "Nestled amidst lush apple orchards and towering cedar and pine forests, Hilltop luxury rooms and 4 rustic cottages, every stay blends comfort with simple Himachali charm. Guests enjoy a top-notch restaurant, banquet hall, swimming pool, and full power backup - perfect for weddings, retreats, or quiet escapes. Located on NH-5 in Narkanda, the resort commands panoramic views of the Himalayas and crisp, pure air all year round. Winters paint the landscape a pristine white; summers bring gentle weather and blooming orchards. Close by are key attractions like Hatu Peak and Tani Jubbar Lake, making adventure and nature walks just a short drive away. Expect warm local hospitality, peace away from city crowds, and moments of true tranquillity at Hilltop.",
    roomMix: ["Deluxe Room - 9 Rooms", "Family Room - 4 Rooms", "Suite - 2 Rooms"],
    roomTypes: [{ name: "Deluxe Room", count: 9 }, { name: "Family Room", count: 4 }, { name: "Suite", count: 2 }],
    features: ["Swimming Pool", "Smoking Rooms", "Power Backup", "Elevator/Lift", "Housekeeping", "Kitchenette", "Laundry Service", "Free Parking"],
    facilities: ["Swimming Pool", "Free Parking", "laundry", "Banquet"],
    amenities: ["Dining Area", "Kids Play Area", "24-hour Room Service", "Bonfire"],
    thingsToDo: ["Narkanda Peak", "Hatu Mata Temple", "Hatu Peak", "Narkanda Market"],
    distances: [{ label: "C h a n d i g a rh In t e r n a t io n al Airpor", km: 170.0 }, { label: "Shimla Railway Station", km: 51.4 }, { label: "Narkanda Bus Stop", km: 12.2 }, { label: "Landmark", km: 13.0 }, { label: "Narkanda Peak Hatu Mata Temple", km: 18.0 }, { label: "Hatu Peak", km: 19.0 }, { label: "Narkanda Market", km: 13.0 }],
    commissionPercent: 14,
  },
  {
    id: "htl-nashik-blvd",
    name: "BLVD",
    shortName: "BLVD",
    city: "Nashik",
    state: "Maharashtra",
    address: "BLVD, Trimbak Road, Satpur, Nashik 422007",
    category: "business",
    status: "active",
    starRating: 4,
    totalRooms: 64,
    description: "BLVD Nashik is a premium lifestyle and event destination located on Trimbak Road, Satpur. Known for its modern design and vibrant atmosphere, it brings together elegant architecture, spacious venues, and thoughtfully curated experiences under one landmark address. The property features versatile banquet halls and open lawns ideal for weddings, corporate events, social gatherings, and celebrations of all sizes. With multiple dining options, cafés, and lounges within the complex, BLVD Nashik offers a seamless blend of celebrations, leisure, and hospitality in the heart of the city.",
    roomMix: ["Executive Rooms - 12 Rooms", "Deluxe Rooms - 18 Rooms", "Superior Rooms - 30 Rooms", "Executive Suite Room - 1 Rooms", "Suite Rooms - 3 Rooms"],
    roomTypes: [{ name: "Executive Rooms", count: 12 }, { name: "Deluxe Rooms", count: 18 }, { name: "Superior Rooms", count: 30 }, { name: "Executive Suite Room", count: 1 }, { name: "Suite Rooms", count: 3 }],
    features: ["Conference Hall", "Housekeeping", "24/7 Hour Reception", "Tea / Coffee Maker", "Furnished Rooms", "Wi-Fi"],
    facilities: ["In Room Dinning", "Lobby", "Banquet"],
    amenities: ["Spa", "Swimming Pool", "Gym", "Laundry"],
    thingsToDo: ["Someshwar Waterfall", "Sula Vineyards", "City Garden"],
    distances: [{ label: "Airport", km: 13.0 }, { label: "Landmark", km: 28.0 }, { label: "Someshwar Waterfall", km: 7.0 }, { label: "Sula Vineyards", km: 8.2 }, { label: "Panchwati", km: 6.5 }, { label: "City Garden", km: 7.2 }, { label: "Dadasaheb Phalke Smarak", km: 8.7 }],
    commissionPercent: 12,
  },
  {
    id: "htl-port-blair-peerless-inn",
    name: "Peerless Inn",
    shortName: "Peerless Inn",
    city: "Port Blair",
    state: "Andaman & Nicobar",
    address: "Port Blair, Andaman & Nicobar",
    category: "business",
    status: "active",
    starRating: 4,
    totalRooms: 49,
    description: "The lush green environment, a coconut palm beach with the sound of the waves makes one forget the hustle and bustle of the city life. This beach resort is a 50 key property fully equipped with modern day",
    roomMix: ["Deluxe Room: 280.52 Sq. Ft. - 34 Rooms", "Sea View Room: 283.26 Sq. Ft. - 12 Rooms", "Cottage Room: 314.84 Sq. Ft. - 3 Rooms"],
    roomTypes: [{ name: "Deluxe Room: 280.52 Sq. Ft.", count: 34 }, { name: "Sea View Room: 283.26 Sq. Ft.", count: 12 }, { name: "Cottage Room: 314.84 Sq. Ft.", count: 3 }],
    features: ["Breakfast", "Free Wi-Fi", "Laundry & Hair Dryer", "Television, Safety Lockers & Telephone", "Mini Bar & Valet parking", "Private Vehicle Parking", "Cubical Glass Bathroom & Car Rental", "Complimentary Water Bottle", "Female Traveler Room / Floor", "Swimming Pool"],
    facilities: ["Sea Sip, offers a wide variety of drinks."],
    amenities: ["Sea Sip, offers a wide variety of drinks."],
    thingsToDo: ["Chidiya Tapu", "Cellular Jail Museum", "Sea Link Adventure", "Marina Park"],
    distances: [{ label: "Port Blair Airport", km: 7.0 }, { label: "Aberdeen Clock Tower", km: 5.9 }, { label: "Cellular Jail Muesum", km: 6.0 }, { label: "Science Centre", km: 2.2 }, { label: "Chatham bridge", km: 10.0 }, { label: "Phoenix Bay Jetty", km: 3.0 }, { label: "Kalapani Museum", km: 6.7 }],
    commissionPercent: 11,
  },
  {
    id: "htl-panhala-hotel-hill-top",
    name: "Hotel Hill Top",
    shortName: "Hill Top",
    city: "Panhala",
    state: "Maharashtra",
    address: "Baji Prabhu Chowk, near Baji Prabhu Deshpande Statue, Panhala, Maharashtra 416201",
    category: "hill_station",
    status: "active",
    starRating: 3,
    totalRooms: 21,
    description: "Nestled at the highest vantage point of Panhala, Hotel Hilltop offers well- furnished rooms and suites overlooking lush green valleys, along with a multi- cuisine restaurant serving both local and international flavours. With spacious lawns, outdoor event areas, ample parking, and easy accessibility for large groups, it creates the perfect setting for leisure and group travel. Perfectly designed for comfort, celebrations, and corporate needs, Hilltop offers banquet halls, event spaces, and conference facilities ideal for weddings, offsites, and social gatherings. Bringing Fidato Hotels' trusted hospitality to the heart of Panhala, the property blends scenic beauty with world-class service for an unforgettable stay.",
    roomMix: ["Executive Rooms - 13 Rooms", "Premier Rooms - 5 Rooms", "Classic Cottage - 2 Rooms", "Suite Cottage - 1 Rooms"],
    roomTypes: [{ name: "Executive Rooms", count: 13 }, { name: "Premier Rooms", count: 5 }, { name: "Classic Cottage", count: 2 }, { name: "Suite Cottage", count: 1 }],
    features: ["Conference Hall", "AC Restaurant", "Children Park & Garden", "Housekeeping", "24/7 Hour Reception", "24/7 Hour Security", "Furnished Rooms", "Panoramic Valley View"],
    facilities: ["Swimming Pool", "Housekeeping", "Banquet"],
    amenities: ["Dining Area", "Food", "24-hour Room Service", "Laundry"],
    thingsToDo: ["Panhala Fort", "Sajja Kothi", "Tabak Udyan", "Teen Darwaja"],
    distances: [{ label: "Airport", km: 21.0 }, { label: "Landmark", km: 20.0 }, { label: "Panhala Fort", km: 0.5 }, { label: "Sajja Kothi", km: 1.2 }, { label: "Tabak Udyan", km: 2.5 }, { label: "Teen Darwaja", km: 3.0 }, { label: "Pusati Buruj", km: 1.8 }],
    commissionPercent: 14,
  },
  {
    id: "htl-pune-hotel-kala-sagar",
    name: "Hotel Kala Sagar",
    shortName: "Kala Sagar",
    city: "Pune",
    state: "Maharashtra",
    address: "Pune, Maharashtra",
    category: "business",
    status: "active",
    starRating: 3,
    totalRooms: 76,
    description: "Hotel Kalasagar is strategically located on the Mumbai-Pune road at Kasarwadi, Pune. It houses 76 exquisitely decorated rooms, range of Banqueting venues, an exotic Multi-cuisine. Restaurants, a state-of- the-art Heath club and Swimming pool.We always consider guest's safety and comfort as our highest priority. As a our trained staff. The hotel is well equipped with metal detectors and other safety equipments. Cleanliness and hygiene is a hallmark of Kalasagar, and is 13 STANDARD ROOMS 23 EXECUTIVE ROOMS 34 DELUXE ROOMS 6 SUPER DELUXE ROOMS",
    roomMix: ["Standard Rooms - 13 Rooms", "Executive Rooms - 23 Rooms", "Deluxe Rooms - 34 Rooms", "Super Deluxe Rooms - 6 Rooms"],
    roomTypes: [{ name: "Standard Rooms", count: 13 }, { name: "Executive Rooms", count: 23 }, { name: "Deluxe Rooms", count: 34 }, { name: "Super Deluxe Rooms", count: 6 }],
    features: ["LCD Interactive TV", "Tea & coffee maker in room with homemade cookies", "In-room electronic safe", "2-hour in-room dining", "Mini-bar", "Foreign currency exchange", "Dry cleaning / laundry services", "Travel desk services", "Doctor on call", "Ample parking facility", "Daily newspaper in rooms"],
    facilities: ["Shehnai 1", "Shehnai 2", "Sitar", "Lawn"],
    amenities: ["Swimming pool", "Sanika Resturant", "Airavat Pure Veg Restaurant", "Gym"],
    thingsToDo: ["Shaniwar Wada", "Aga Kha Palace", "Sinhagad Fort", "Pataleshwar Caves"],
    distances: [{ label: "Pune Airport", km: 15.5 }, { label: "Pune Railway Station", km: 13.5 }, { label: "Koregaon Park", km: 13.2 }, { label: "Chakan", km: 20.4 }, { label: "Chinchwad", km: 6.1 }, { label: "Hinjewadi", km: 13.4 }, { label: "Kharadi", km: 19.2 }],
    commissionPercent: 13,
  },
  {
    id: "htl-pune-marigold",
    name: "Marigold",
    shortName: "Marigold",
    city: "Pune",
    state: "Maharashtra",
    address: "Opp, Windmill Village Rd, Windmill Village, Bavdhan, Pune, Maharashtra 411021",
    category: "banquet",
    status: "active",
    starRating: 4,
    totalRooms: 150,
    description: "Marigold Banquets & Conventions is a luxurious multipurpose venue crafted to host celebrations of every kind - from grand weddings and lavish receptions to intimate gatherings and corporate events. Step into an ambiance of refined elegance, where royal interiors, plush décor, and modern amenities come together seamlessly. Designed to perfection, Marigold offers versatile event spaces, personalized hospitality, and an experienced team dedicated to turning your vision into here radiates sophistication and warmth.",
    roomMix: ["Suite Room - 5 Rooms", "Deluxe Room - 115 Rooms", "Business Class - 30 Rooms"],
    roomTypes: [{ name: "Suite Room", count: 5 }, { name: "Deluxe Room", count: 115 }, { name: "Business Class", count: 30 }],
    features: ["Wifi", "Housekeeping", "24/7 Hour Reception", "24/7 Hour Security", "Mini Bar", "Parking"],
    facilities: ["Conference Hall", "Housekeeping", "Banquet"],
    amenities: ["Dining Area", "Food", "24-hour Room Service", "Laundry"],
    thingsToDo: ["Joshi's Museum Of Miniature", "Pashan Lake View Point", "Bavdhan Tekdi", "Shaniwar Wada"],
    distances: [{ label: "Airport -Pune", km: 24.0 }, { label: "Satara", km: 17.0 }, { label: "Miniature Railways", km: 7.4 }, { label: "Joshi's Museum Of Pashan Lake View Point", km: 6.0 }, { label: "Bavdhan Tekdi", km: 5.0 }, { label: "Shaniwar Wada", km: 11.4 }, { label: "Laal Mahaal", km: 16.0 }],
    commissionPercent: 12,
  },
  {
    id: "htl-pune-silver-crest",
    name: "Silver Crest",
    shortName: "Silver Crest",
    city: "Pune",
    state: "Maharashtra",
    address: "Pune, Maharashtra",
    category: "business",
    status: "active",
    starRating: 3,
    totalRooms: 24,
    description: "The property in Pune is within a range of 1 km from the Pune Lohegaon Airport and the Phoenix Market City. Guests have the option to choose from its 24 well-kept rooms that are fitted with ceiling fan and en-suite bathroom. Silver Crest Viman Nagar provides room service. Furthermore, the accommodation in Pune has a front desk available on the premises. 24 WELL-KEPT ROOMS: 250 Sq. ft.",
    roomMix: ["Well-kept Rooms: 250 Sq. Ft. - 24 Rooms"],
    roomTypes: [{ name: "Well-kept Rooms: 250 Sq. Ft.", count: 24 }],
    features: ["Breakfast", "Silver Crest", "Pune", "Free Wi-Fi", "Attached Washrooms", "Television & Safety Lockers", "Luxurious Linens & Towels", "Laundry Service", "Car Rental", "Doctor On Call", "Air-Conditioned", "Property Tour", "Garden at Entrance", "Backyard Garden"],
    facilities: [],
    amenities: [],
    thingsToDo: [],
    distances: [{ label: "Pune Airport", km: 1.0 }, { label: "Pune Station", km: 9.0 }, { label: "Shaniwar Wada Palace", km: 11.0 }, { label: "Phoenix Mall", km: 1.5 }, { label: "Aga Khan Palace", km: 3.0 }, { label: "World Trade Center", km: 6.0 }, { label: "Osho Garden", km: 5.5 }],
    commissionPercent: 13,
  },
  {
    id: "htl-pune-sadanand-regency",
    name: "Sadanand Regency",
    shortName: "Sadanand Regency",
    city: "Pune",
    state: "Maharashtra",
    address: "9/2, 9/2, National Highway 4, Patil Nagar, Balewadi, Pune, Maharashtra, 411045, India",
    category: "business",
    status: "active",
    starRating: 3,
    totalRooms: 82,
    description: "The 3-star Hotel Sadanand Regency in Pune offers a terrace and free Wi-Fi throughout. The hotel features 111 air-conditioned rooms with flat-screen TVs and minibars. Rooms are elegantly furnished, and private bathrooms have a shower and separate toilet. Guests can enjoy breakfast in the on-site restaurant. The hotel also has a sports complex, meeting rooms, and a business center. Located about 25 minutes' walk from Kirloskar Group and 10 minutes' drive from Sunset View Point Baner Nature Preserve, the hotel is also near Balewadi Sports Complex (3.4 km) and Datta Mandir (10 minutes' drive). It is 30 km from Pune International Airport and close to the Balewadi depot bus station.",
    roomMix: ["Standard Room - 46 Rooms", "Deluxe Room - 26 Rooms", "Suite - 10 Rooms"],
    roomTypes: [{ name: "Standard Room", count: 46 }, { name: "Deluxe Room", count: 26 }, { name: "Suite", count: 10 }],
    features: ["Dry Cleaning Service", "Lounge", "Free Wi-Fi", "24-hour Room Service", "Power Backup", "Private Entrance"],
    facilities: ["Dry Cleaning Service", "Power Backup", "Free WiFi"],
    amenities: ["Bar", "Banquet", "Swimming Pool"],
    thingsToDo: ["Sinhagad Fort", "Shaniwar Wada", "Aga Khan Palace", "Pataleshwar Caves"],
    distances: [{ label: "Pimpri Station", km: 14.8 }, { label: "Pune Junction", km: 19.0 }, { label: "Airport", km: 22.0 }, { label: "Bus Stand", km: 1.8 }, { label: "Landmark", km: 20.0 }, { label: "Shaniwar Wada Aga Khan Palace", km: 19.0 }, { label: "Pataleshwar Caves", km: 19.5 }],
    commissionPercent: 13,
  },
  {
    id: "htl-rajkot-patria-suites",
    name: "Patria Suites",
    shortName: "Patria Suites",
    city: "Rajkot",
    state: "Gujarat",
    address: "Rajkot, Gujarat",
    category: "business",
    status: "active",
    starRating: 4,
    totalRooms: 94,
    description: "\"Patria Suites\" All suite room hotel with redefined luxury serviced apartments set in the heart of the bustling city of Rajkot, Patria Suites is a swanky business hotel in Rajkot, located in close proximity to Rajkot Airport, Rajkot Railway Station, and major business centers in the city. Patria Suites offers a range of facilities to ensure a comfortable stay for our esteemed guests. Spacious and contemporary accommodations come in four categories - Corporate Room & Luxury Suite, The Patria Suites has two dining choices - Coconut Groove one of the most well-known vegetarian restaurants in Rajkot, You can enjoy our specially crafted food menu at the flight's landing and takeoff from the adjacent airport with a soothing atmosphere in the evening or sit at pool deck.",
    roomMix: ["Studio Suite - 52 Rooms", "One Bedroom Suite - 30 Rooms", "Premium Suite - 12 Rooms"],
    roomTypes: [{ name: "Studio Suite", count: 52 }, { name: "One Bedroom Suite", count: 30 }, { name: "Premium Suite", count: 12 }],
    features: ["Fitness centre & GYM", "Spa", "Mini - Theatre", "Game Zone", "Aqua Massage Jacuzzi", "Swimming Pool"],
    facilities: ["Party Lounge", "Fitness centre & GYM", "Spa", "Mini - Theatre"],
    amenities: ["Swimming Pool", "Game Zone", "Aqua Massage Jacuzzi", "The Boardroom"],
    thingsToDo: ["Sardar Vallabhbhai Patel Waterfall", "Mahatma Gandhi Museum", "Pradhyuman Zoological Park", "Fun World"],
    distances: [{ label: "AIRP O R T MAIN Railw a y S t ation", km: 2.6 }, { label: "Maha t m a G andhi M u s e u m", km: 3.0 }, { label: "P ra d h y um a n Zo o lo g i ca l P a rk", km: 7.0 }, { label: "Fun World", km: 2.1 }, { label: "Sa r d a r V a ll a b h b h ai P a t e l W a t e", km: 1.7 }, { label: "Landmark", km: 1.3 }],
    commissionPercent: 12,
  },
  {
    id: "htl-shantiniketan-titli-resort",
    name: "Titli Resort",
    shortName: "Titli Resort",
    city: "Shantiniketan",
    state: "West Bengal",
    address: "Sonajhuri Rd, haat, Santiniketan, Kabi Mohanpur, West Bengal 731235",
    category: "resort",
    status: "onboarding",
    starRating: 3,
    totalRooms: 36,
    description: "Welcome to Resort Titli, Santiniketan Come, experience the privacy and natural setting of our boutique resort providing 4 star facilities. With our property stretching across 2 acres of park-like land it boasts gentle landscape alongside steep cliffs overlooking the green an intimate and private atmosphere. Our resort is ideally located, giving you the privacy of paradise, while also offering access to all the sights and sounds 'Titli' has to offer. 'Titli' has created lasting and vivid memories for guests worldwide, let us have a place in your heart as well. Book your holiday getaway today!",
    roomMix: ["Cottage - 22 Rooms", "Deluxe Cottage - 10 Rooms", "Suite - 4 Rooms"],
    roomTypes: [{ name: "Cottage", count: 22 }, { name: "Deluxe Cottage", count: 10 }, { name: "Suite", count: 4 }],
    features: ["Free Wifi", "Daily Housekeeping", "Free Parking", "Cable TV"],
    facilities: ["On Site Parking", "Cable TV", "Free WiFi"],
    amenities: ["Swimming Pool", "Gym", "Lounge"],
    thingsToDo: ["Amar Kutir Society For", "Kankalitala Shaktipeeth Temple", "Shonajhuri Haat", "Srijani Shilpagram", "Add languages"],
    distances: [{ label: "Bolpur bus stand", km: 5.0 }, { label: "Prantik Rail Station", km: 3.0 }, { label: "Kazi Nazrul - Andal Air Port", km: 74.0 }, { label: "Kankalitala Shaktipeeth Temple", km: 7.5 }, { label: "Biswabharati University", km: 3.5 }, { label: "Santiniketan", km: 3.5 }],
    commissionPercent: 14,
  },
  {
    id: "htl-solapur-hotel-center-point",
    name: "Hotel Center Point",
    shortName: "Center Point",
    city: "Solapur",
    state: "Maharashtra",
    address: "Solapur, Maharashtra",
    category: "business",
    status: "active",
    starRating: 3,
    totalRooms: 68,
    description: "Hotel Center Point, Solapur is a contemporary mid-scale hotel and as the name suggests, is located in the heart of the city and in close proximity to the upcoming airport, railway station and bus stand. The hotel offers 34 rooms including suites along with Palkhi, a vegetarian multi-cuisine restaurant and a banquet hall for meetings and corporate events. The hotel offers an optimum blend of comfort, efficient services and convenience for business travellers. Each room is complete with luxurious beds, premium furnishings, wi-fi connectivity and other in-room",
    roomMix: ["Total Rooms - 34 Rooms", "Deluxe Rooms - 18 Rooms", "Executive Rooms - 12 Rooms", "Suite Room - 4 Rooms"],
    roomTypes: [{ name: "Total Rooms", count: 34 }, { name: "Deluxe Rooms", count: 18 }, { name: "Executive Rooms", count: 12 }, { name: "Suite Room", count: 4 }],
    features: ["Free Wi-Fi", "Multi Cuisine Restaurant", "Tea/Coffee Maker", "Free Parking"],
    facilities: ["Multi Cuisine Restaurant", "Banquet Hall"],
    amenities: [],
    thingsToDo: ["Siddheshwar Temple", "Bhuikot Fort", "Solapur Science Center", "Swami Samarth Mandir"],
    distances: [{ label: "Solapur Airport", km: 5.2 }, { label: "Solapur", km: 1.5 }, { label: "Solapur Bus Stand", km: 3.4 }, { label: "Siddheshwar Temple", km: 2.1 }, { label: "Bhuikot Fort", km: 2.6 }, { label: "Swami Samarth Mandir", km: 5.2 }, { label: "Solapur Science Center", km: 11.2 }],
    commissionPercent: 13,
  },
  {
    id: "htl-udaipur-the-crescent",
    name: "The Crescent",
    shortName: "Crescent",
    city: "Udaipur",
    state: "Rajasthan",
    address: "Krishna complex, A-8, Trident Rd, Haridas Ji Ki Magri, Shavri Colony, Udaipur, Rajasthan 313001",
    category: "heritage",
    status: "active",
    starRating: 4,
    totalRooms: 17,
    description: "The Crescent - A Boutique Hotel Udaipur, managed by Fidato Hotels and a part of Skylark Hospitality, is a luxurious property located on Trident Road, Haridas Ji Ki Magri, offering stunning views of Lake Pichola. With 17 elegantly appointed rooms, the hotel combines modern amenities and personalized Indian service for an unforgettable experience. Features include a rooftop guests ideal for weddings and events, and a prime location near Udaipur's famous landmarks. Guests also enjoy convenient parking and high-value",
    roomMix: ["Heritage Room - 10 Rooms", "Lake View Room - 5 Rooms", "Royal Suite - 2 Rooms"],
    roomTypes: [{ name: "Heritage Room", count: 10 }, { name: "Lake View Room", count: 5 }, { name: "Royal Suite", count: 2 }],
    features: ["Banquet Hall", "Lounge", "Free Wi-Fi", "Spa & Swimming Pool", "Convenient Parking"],
    facilities: ["Convenient Parking", "Power Backup", "Free WiFi"],
    amenities: ["Lounge", "Banquet", "Swimming Pool"],
    thingsToDo: ["City Palace of Udaipur", "Lake Pichola", "Bagore Ki Haveli Museum", "Ambrai Ghat"],
    distances: [{ label: "Landmark", km: 5.5 }, { label: "Airport", km: 9.5 }, { label: "City P a l a ce of U d a i p u r", km: 2.0 }, { label: "Lake Pichola", km: 3.3 }, { label: "Bago r e K i H aveli M u s e u m", km: 1.7 }, { label: "Ambrai Ghat", km: 1.6 }, { label: "Fateh Sagar lake", km: 1.3 }],
    commissionPercent: 12,
  },
];
